<?php

namespace Tests\Feature\Controllers;

use Illuminate\Http\Response;
use Playlog\Comment;
use Playlog\User;
use Tests\TestCase;

class CommentReactionControllerTest extends TestCase
{
	protected User $user;

	public function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->user = factory(User::class)->create();
	}

	/**
	 * @test
	 */
	public function it_responds_with_a_422_if_the_comment_content_is_not_given()
	{
		$this->actingAs($this->user);
		$this->json('POST', '/comments', ['content' => 'lorem ipsum', 'author_id' => $this->user->getKey()]);
		$comment = Comment::all()->last();

		$this->json('POST', '/reactions/', [
			'author_id' => $this->user->getKey(),
			'comment_id' => $comment->getKey()
		])->assertStatus(Response::HTTP_UNPROCESSABLE_ENTITY)
			->assertJsonValidationErrors(['content']);
	}
}